Features
AbdallahJumah95/Programmer-s_portfolio pull request #1
Opened 2023-05-06 12:59 UTC by AbdallahJumah95

in this project I have (so far) :

- create .gitignore and node_moudles
-create .github file and add some content
-added linters
-fixed all linters

2023-05-06 16:13 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @AbdallahJumah95 , 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 16:13 UTC, anagudelogu commented on README.md
> +**[Hello Microverse]** First project in microverse!
- [ ] You did a good job working on your project documentation! However, please make sure to include the information for the right project as the `Hello Microverse` is a different one. 🤓 🔧

2023-05-06 16:13 UTC, anagudelogu commented on README.md
>  ## 🛠 Built With <a name="built-with"></a>
- [ ] Please also consider listing the technologies you used to build this project, in this case, HTML and CSS. 🤓 🔧

2023-05-06 16:13 UTC, anagudelogu commented on README.md
> +This project is [MIT](./mit.md) licensed.
- [ ] You did a great job working on this milestone! 🚀 However, to ensure your documentation is professional, please always double-check that all links are working. Currently, your license link is broken due to a typo in its name, this link is looking for a file named `mit.md` but the actual name is `MIT.md`. Please consider fixing this! 🤓 🔧

2023-05-06 16:13 UTC, anagudelogu commented on index.html
> +<body>
- [ ] Please consider taking a look at this:

![image](https://user-images.githubusercontent.com/77069011/236634493-d6f418dd-7a60-4394-ad28-5375c3f37ae9.png)

This is what I see when I run your project locally, it looks like you don't have an `images` folder. Please fix this and make sure to match the given FIGMA design! 🤓 🔧

2023-05-06 16:13 UTC, anagudelogu commented on index.html
> +    </header>
You did a great job using the `<header>` tag 💯 , however, I have some observations regarding the semantics of this section:

- [ ] Please consider wrapping your Logo in a `<a>` tag, this is because, by convention, the logo of a page should redirect the user to the home page, improving the experience browsing your site! 🤓 

- [ ] Navigation links are not yet required, remember that we're going to follow a mobile-first approach where you are going to start developing the mobile version and later on, making it responsive to other screen sizes, instead, please include a hamburger icon and wrap it inside a `<nav>` tag to indicate that this element is in charge of the navigation! 🤓

2023-05-06 16:13 UTC, anagudelogu commented on index.html
> +      <h1 class = "h2">Glad To see you!</h1>
- [ ] Please avoid having multiple `<h1>` tags on the same page, as this tag has a special meaning for search engines and it should represent the main content of your page, instead, consider using `<h2>` which I see you used it as a class. 🤓 🔧

2023-05-06 16:13 UTC, anagudelogu commented on index.html
> +          <p class = "p"> let's connect </p>
- [ ] This element acts as a header for the social media icons list, so it would be better described if you use one of the heading tags `<h2>`...`<h6>`. 🤓 🔧

2023-05-06 16:13 UTC, anagudelogu commented on index.html
> +            </div>
- [ ] This represents a list of social media icons, so in order for this to be better described to the browser, I suggest you use the `<ul>` tag, and wrap each of the icons inside an `<li>`, something like this: 🤓 🔧 

```html
<ul>
  <li> <a href="(link to your social media here)"> icon1 </a> </li>
  <li> <a href="(link to your social media here)"> icon2 </a> </li>
  ...
</ul>

```

2023-05-06 16:13 UTC, anagudelogu commented on index.html
> +      <img class ="img10" SRC="/images/Ellipse 13.png">
- [ ] I assume you're using these images to style the background of your page, however, I encourage you to download the complete image from FIGMA, as this is purely aesthetic and doesn't have any meaning to the content of your page, you define it as a `background-image` in CSS, without using any HTML tags. 🤓 🔧

2023-05-06 16:13 UTC, anagudelogu commented on index.css
> +}
- [ ] According to the requirements:

![image](https://user-images.githubusercontent.com/77069011/236635177-2f7b6076-c4f0-4ab1-b4de-100286a05bf1.png)

Please consider using `flexbox` to layout your header section! 🤓 🔧

2023-05-06 19:35 UTC, AbdallahJumah95 commented
please just approve it, and don't demand for more adjustment, there isn't much left to the deadline, and I really want to get one r and done with this please just approve it and let me pass I will adjust later, all the adjustments

2023-05-07 04:29 UTC, Efiamotu-1 commented
@AbdallahJumah95 i am sorry and i understand your frustration, but granting your request is not how things work for reviewers at microverse in as much as we want students to pass to the next project or milestone we also want to see that the student has mastered the required skill for the present milestone and to do so your project is expected to meet the standards set by the previous reviewer, so i will indulge you and kindly please request that wihile you still have about 1hr 30mins left you should work on the most significant changes you can make to the very best and resubmit again even if it is not fully completed and state in your submission how much you have done and what is left and the next reviewer might to his own discretion approve your project and allow you complete the remaining part after. BUT please you need to first work on the major aspects of the required changes from your first review. 
- I am really looking forward to seeing that you resubmit and get approved as you would like before the deadline :sparkles: :grin: :+1:

2023-05-07 04:29 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @AbdallahJumah95  , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

✅ Descriptive Pull Request title and summary. ✔️
✅ Good use of Github flow ✔️
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

### Changes Required

- [ ] please you have not implement all the changes requested by your previous code reviewer please kindly fix all before resubmit for the next review this a drilling to make you a perfect professional developer ,the beginning might look like this, but end you will proud of yourself we believe in you success has no limit for you to achieve.
- I will be happy to see your project got approved before the deadline time.

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-07 04:29 UTC, ademibowale commented on index.html
> +      <img src="/images/Unknown.png" alt="Abdallah's portfolio", height= "200px" width="200px">
- [ ] you have done a great job on this project I would kindly suggest you to take a good look at the figma design template so as to build your website portfolio in standard , According to the previous reviewer Please consider wrapping your Logo in a <a> tag, this is because, by convention, the logo of a page should redirect the user to the home page, improving the experience browsing your site! 
- [ ] Please I would suggest you kindly follow the project guildline, according to your previous reviewer Navigation links are not yet required, remember that we're going to follow a mobile-first approach where you are going to start developing the mobile version and later on, making it responsive to other screen sizes, instead, please include a hamburger icon and wrap it inside a <nav> tag to indicate that this element is in charge of the navigation!

2023-05-07 04:29 UTC, ademibowale commented on index.html
> +    <section class="container">
- [ ] According to your previous reviewer please kindly avoid having multiple `h1` tag,on the same page has this tag has a special meaning for search engin and it should represent main content of your page instead I would suggest you consider using `h2`

2023-05-07 04:29 UTC, ademibowale commented on index.html
> +      <p>I am a software developer! I can help you build a product,
- [ ] According to your previous reviewer This element acts as a header for the social media icons list, so it would be better described if you use one of the heading tags `<h2>``<h6>`.Please kindly follow the guildline to fix this

2023-05-07 04:29 UTC, ademibowale commented on index.html
> +            <a href="#" class="fa fa-facebook" ></a>
- [ ] According to your previous reviewer kindly consider to use `ul` tag and wrap each of the icons inside `<li>` it represent a list of media icons it will indicate it better on your website UI

- [ ] please when I run your project locally this is what I see non of your images have show please fix this 
![snapshot_rawcdn githack com_1683430060834](https://user-images.githubusercontent.com/92458236/236657320-e58a2c4f-ee14-4eee-a1a5-c72c0a17f94d.png)

2023-05-07 04:29 UTC, ademibowale commented on index.html
> +      <img class ="img1" SRC="/images/Ellipse 11.png">
- [ ] please kindly implement all changes requested from your previous reviewer has all this changes listed is very essential base on the project requirement and you will surely proud of yourself at the end of this milestone.please I kindly  make sure you implement all this changes before you resubmit for the next review.

2023-06-10 21:48 UTC, closed without merging